name: Node.js CI

on: [push]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - run: sudo gem install bundler:1.17.2
      - uses: actions/cache@v2
        with:
          path: api/vendor/bundle
          key: ${{ runner.os }}-gems-${{ hashFiles('**/Gemfile.lock') }}
          restore-keys: |
            ${{ runner.os }}-gems-
      - name: Install gemfilee
        run: |
          cd api
          bundle config path vendor/bundle
          bundle install
      - name: Rubocop
        run: cd api && bundle exec rubocop -c .rubocop.yml
      - name: Rails Best Practices
        run: cd api && bundle exec rails_best_practices -e "db/schema.rb,db/migrate,vendor,app/models/application_record.rb"
      - name: Rpec
        run: cd api && bundle exec rspec --format documentation
      - name: reek
        run: cd api && bundle exec reek
