name: Node.js CI

on: [push]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - run: cd api
      - run: |
          sudo curl -o /usr/bin/framgia-ci https://raw.githubusercontent.com/framgia/ci-report-tool/master/dist/framgia-ci
          sudo chmod +x /usr/bin/framgia-ci
          sudo apt install python3-pip
          sudo apt install libcurl4-openssl-dev libssl-dev
      - run: pip3 install framgia-ci
      - run: pip3 uninstall cleo clikit
      - run: pip
      - run: pip3 install cleo==0.6.8
      - name: Run CI
        run: framgia-ci run --local
