name: Node.js CI

on: [push]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - run: |
          cd api
          ls -la
      - run: |
          sudo curl -o /usr/bin/framgia-ci https://raw.githubusercontent.com/framgia/ci-report-tool/master/dist/framgia-ci
          sudo chmod +x /usr/bin/framgia-ci
          sudo apt install python3-pip
          sudo apt install libcurl4-openssl-dev libssl-dev
          sudo apt-get install -y python3-setuptools
      - run: |
          yes | pip3 install wheel
          pip3 install framgia-ci
          pip3 uninstall --yes cleo clikit
          yes | pip3 install cleo==0.6.8
      - name: Run CI
        run: framgia-ci run
